### ISSUE TITLE
Typo in (a, b) constant requirements

### ISSUE THREAD

**Issue by michaelforney** [doubleodd/doubleodd-doc#1]
In section 2 of the -jq whitepaper, Background on Double-Odd Curves, it says

> For any two constants (a, b) ∈ Fq × Fq such that a ∉ QR and a² − 4b ∉ QR, ...

I believe that "a ∉ QR" should be "b ∉ QR", since that matches the original whitepaper and the website, and is what is later assumed in section 3.

**Comment by michaelforney** [comment]
Ping @pornin

**Comment by pornin** [comment]
This is true. This is now fixed. Thanks!
